baseURL = "https://www.checkerbloommusic.com/"
languageCode = "en-us"
title = "Check Bloom"
theme = "github.com/themefisher/northendlab-hugo"
paginate = "5"
summaryLength = "10"
disqusShortname = "" # get your shortname form here : https://disqus.com

[params]
home = "Home"
logo = "images/logo_text.png"
author = "Checker Bloom"
description = "Four-piece rock band based in Bellingham, WA"
google_tag_manager = "" # your id
google_analitycs_id = "" # your id
contact_form_action = "#" # contact form works with : https://formspree.io
copyright = "&copy; 2021 Checker Bloom All Rights Reserved"

[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

[params.search]
enable = false

[params.banner]
bgImage = "images/banner/checker_bloom_flower.jpeg"
#title = ""
image = "images/banner/logo-rotated-cropped.svg"

[params.cta]
enable = true
image = "images/banner/logo-rotated-cropped.svg"
title = "Become a Checker Bloom Bud"
description = "Subscribe for relevant updates. We won't spam you!"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"

[params.contact]
enable = true
title = "Let us know what is on your mind"
description = "We'll get back to you as soon as possible!"

[[params.social]]
icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
link = "https://www.facebook.com/checkerbloommusic"
[[params.social]]
icon = "ti-instagram" # themify icon pack https://themify.me/themify-icons
link = "https://www.instagram.com/checkerbloommusic/"

[[menu.main]]
URL = "#events"
name = "Events"
weight = 1

[[menu.main]]
URL = "#subscribe"
name = "Subscribe"
weight = 2

[[menu.main]]
URL = "#contact"
name = "Contact"
weight = 3

[[menu.footer]]
URL = "#events"
name = "Events"
weight = 1

[[menu.footer]]
URL = "#subscribe"
name = "Subscribe"
weight = 2

[[menu.footer]]
URL = "#contact"
name = "Contact"
weight = 3

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/custom.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
